config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  constraints ->(request) { request.env['warden'].user&.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  mount Sidekiq::Web => '/sidekiq'

  root 'dreams#index', defaults: { format: :html }

  resources :categories, only: %i[index show]

  resources :dreams do
    resources :comments
    post :search, on: :collection
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only: %i[show edit update]
end

app/models/dream.rb
class Dream < ApplicationRecord
  searchkick
  scope :search_import, -> { includes(:tags) }

  belongs_to :user
  belongs_to :category, counter_cache: :dreams_count
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
  has_one_attached :image, dependent: :destroy

  validates :date, presence: true, date: { after: proc { Time.zone.today - 100.years },
                                           before: proc { Time.zone.tomorrow } }
  validates :duration, presence: true, numericality: { in: 0..24 }
  validates :title, presence: true, length: { in: 3..50 }
  validates :description, length: { maximum: 2500 }

  def search_data
    {
      title:,
      description:,
      date:,
      tags: tags.map(&:name)
    }
  end

  def to_csv
    CSV.generate do |csv|
      csv << %w[title description category_name user_name tags]
      csv << [title, description, category.name, user.name, tags.map(&:name).join(',')]
    end
  end
end

app/controllers/avo/dreams_controller.rb
class Avo::DreamsController < Avo::ResourcesController
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :find_dream, only: %i[show edit update destroy]
  authorize_resource

  def index
    @pagy, @dreams = pagy_countless(Dream.def_includes.order(created_at: :desc), items: 20)
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = current_user.dreams.new(dream_params)
    if @dream.save
      set_tags
      redirect_to dream_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @dream.update(dream_params)
      set_tags
      redirect_to dream_path(@dream)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    render :error, status: :not_found unless @dream
    @comments = @dream.comments.where(parent_id: nil)
    respond_to do |format|
      format.html
      format.csv { send_data @dream.to_csv, filename: %(dreams-#{DateTime.now.strftime('%d%m%Y%H%M')}.csv) }
    end
  end

  def destroy
    @dream.destroy
    redirect_to user_path(current_user)
  end

  def search
    search_field = (search_params[:search].presence || '*')
    date = search_params[:date].presence

    @dreams = if search_params[:search].start_with?('#')
                tag_name = search_params[:search].delete_prefix('#')
                where_scope = { tags: tag_name }
                where_scope[:date] = date if date
                Dream.search(tag_name, fields: %i[tags], where: where_scope)
              elsif date
                Dream.search(search_field, fields: %i[title description date], where: { date: })
              else
                Dream.search(search_field, fields: %i[title description])
              end.includes(:image_blob, :category, :user)
    render turbo_stream: turbo_stream.update('dreams', partial: 'dreams', locals: { dreams: @dreams })
  end

  private

  def dream_params
    params.require(:dream).permit(:date, :duration, :title, :description, :image, :category_id)
  end

  def tags_params
    params[:dream][:tags].reject(&:blank?)
  end

  def find_dream
    @dream = Dream.find(params[:id])
  end

  def set_tags
    @tags = Tag.where(name: tags_params)
    @dream.tag_ids = @tags.pluck(:id)
  end

  def search_params
    params.require(:search).permit(:search, :date)
  end
end

app/views/dreams/_dreams.html.erb
<div class="row row-cols-1 row-cols-md-5 g-4 pb-4">
  <% dreams.each do |dream| %>
    <div class="col">
      <div class="card h-100">
        <%= link_to dream_path(dream), class: "card-link" do %>
          <% if dream.image.attached? %>
            <%= image_tag dream.image, class: "card-img-top", style: 'max-height:150px;' %>
          <% else %>
            <%= image_tag 'default_dream_image.jpg', class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= dream.title %></h5>
            <p class="card-text"><%= dream.user.name %></p>
          </div>
        <% end %>
        <div class="card-footer">
          <small class="text-body-secondary"><%= time_ago_in_words(dream.created_at) + t('.ago') %> </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dreams/_form.html.erb
<%= simple_form_for @dream do |f| %>
  <div>
    <%= f.input :date %>
    <%= f.input :duration, as: :select, collection: (0..24).to_a, selected: 8, prompt: 'Select duration' %>
    <%= f.association :category %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image, as: :file, input_html: { accept: User::AVATAR } %>
    <%= f.input :tags, as: :check_boxes, collection: Tag.pluck(:name), wrapper: :vertical_collection_inline, checked: @dream.tags.pluck(:name) %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dreams/edit.html.erb
<%= render 'form', dream: @dream %>

app/views/dreams/error.html.erb
<%= image_tag "https://http.cat/#{response.status}", class: 'rounded mx-auto d-block' %>

app/views/dreams/index.html.erb
<%= render 'categories/group' %>

<div id='dreams_category'>
  <div id="dreams_pagy"></div>
</div>

<%= turbo_frame_tag "pagination", src: dreams_path(format: :turbo_stream), loading: :lazy %>

app/views/dreams/index.turbo_stream.erb
<%= turbo_stream.append 'dreams_pagy' do %>
   <%= render partial: 'dreams/dreams', locals: { dreams: @dreams } %>
 <% end %>
<% if @pagy.next.present? %>
  <%= turbo_stream.replace 'pagination' do %>
    <%= turbo_frame_tag 'pagination', src: dreams_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/dreams/new.html.erb
<%= render 'form', dream: @dream %>

app/views/dreams/show.html.erb
<% content_for :title do %>
  <%= @dream.title %>
<% end %>

<div class="card border-0 shadow-sm">
  <div class="card-body">
    <div class="row">
      <div class="col-md-4 mb-4 mb-md-0">
        <% if @dream.image.attached? %>
          <%= image_tag @dream.image, class: "img-fluid rounded", alt: 'Dream image', style: "width: 500px;" %>
        <% else %>
          <%= image_tag 'default_dream_image.jpg', class: "img-fluid rounded", alt: 'Dream image', style: "width: 500px;" %>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="p-3 mb-4">
          <%= image_tag @dream.user.avatar, class: 'rounded-circle', style: 'width: 50px' %>
          <div class="d-inline-block">
            <h4 class="mb-0"><%= @dream.user.name %></h4>
            <p class="m-0 text-muted"><%= @dream.date %></p>
            <h4 class="m-0 text-muted"><%= @dream.duration %></h4>
          </div>
        </div>
        <h1 class="card-title h4 mb-4"><%= @dream.title %></h1>
        <% @dream.tags.each do |tag| %>
          <%= link_to search_dreams_path(search: { search: "##{tag.name}"}), data: { turbo_method: :post }, class: 'badge bg-info text-dark me-2' do %>
            <%= tag.name %>
          <% end %>
        <% end %>
        <p class="card-text"><%= @dream.description %></p>
      </div>
    </div>
  </div>
  <div class='card-footer'>
    <%= link_to 'Edit', edit_dream_path(@dream), class: 'btn btn-secondary me-2' if can? :update, @dream %>
    <%= link_to (octicon "download", height: 30), dream_path(@dream, format: :csv) %>
  </div>
</div>

<%= render template: 'comments/index', comments: @comments %>