config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  constraints ->(request) { request.env['warden'].user&.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  mount Sidekiq::Web => '/sidekiq'

  root 'dreams#index', defaults: { format: :html }

  resources :categories, only: %i[index show]

  resources :dreams do
    resources :comments
    post :search, on: :collection
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only: %i[show edit update]
end

app/models/user.rb
class User < ApplicationRecord
  AVATAR = Mime::LOOKUP.keys.keep_if { |v| v =~ /image/ }

  has_many :dreams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :validatable, :confirmable,
         omniauth_providers: %i[google_oauth2]

  enum :status, { active: 0, blocked: 1 }
  enum :role, { user: 0, admin: 1 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.avatar_url = auth.info.image
      user.avatar.attach(io: URI.open(auth.info.image), filename: 'avatar.jpg')
      user.skip_confirmation!
      user.save!
    end
  end
end

app/controllers/avo/users_controller.rb
class Avo::UsersController < Avo::ResourcesController
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} not auth-ed"
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: :create

    def create
      super do |user|
        if params[:avatar].present?
          user.avatar.attach(params[:avatar])
        else
          user.avatar.attach(io: File.open('app/assets/images/default_avatar.jpg'), filename: 'default_avatar.jpg')
        end
      end
    end

    protected

    def after_inactive_sign_up_path_for(_resource)
      new_user_session_path
    end

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email avatar])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @dreams = current_user.dreams.order(created_at: :desc)
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to user_path, notice: 'Profile updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/views/users/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Oh, it can also lead to poor sleep.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Delete', dream_path(dream), class: "btn btn-danger", data: { turbo_method: :delete } %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= simple_form_for current_user, html: { multipart: true } do |f| %>
      <h1>Edit Profile</h1>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :avatar, as: :file, input_html: { accept: User::AVATAR } %>
      <%= f.button :submit, class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card mb-3">
      <%= image_tag current_user.avatar, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= current_user.name %></h5>
        <p class="card-text"><%= current_user.email %></p>
        <%= link_to "Edit Profile", edit_user_path, class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <% if @dreams.any? %>
      <div class="card-deck">
        <% @dreams.each do |dream| %>
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title"><%= dream.title %></h5>
              <p class="card-text"><%= dream.description %></p>
              <%= link_to "Show", dream_path(dream), class: "btn btn-primary" %>
              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Delete
              </button>
              <%= render 'modal', dream: %>
            </div>
            <div class="card-footer">
              <small class="text-muted"><%= dream.date.strftime("%B %d, %Y") %></small>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>No dreams found.</p>
    <% end %>
  </div>
</div>