config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  constraints ->(request) { request.env['warden'].user&.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  mount Sidekiq::Web => '/sidekiq'

  root 'dreams#index', defaults: { format: :html }

  resources :categories, only: %i[index show]

  resources :dreams do
    resources :comments
    post :search, on: :collection
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only: %i[show edit update]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dreams, dependent: :nullify
  has_one_attached :image, dependent: :destroy
  enum :status, { active: 0, archived: 1 }

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/avo/categories_controller.rb
class Avo::CategoriesController < Avo::ResourcesController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: :show

  def show
    @dreams = @category.dreams.def_includes.order(created_at: :desc)
    render turbo_stream: turbo_stream.update('dreams_category', partial: 'dreams/dreams',
                                                                locals: { dreams: @dreams })
  end

  private

  def find_category
    @category = Category.find_by(id: params[:id])
  end
end

app/views/categories/_group.html.erb
<div class="mb-3">
  <%= link_to "All", dreams_path, class: "btn btn-dark my-1" %>
  <% Category.active.where('dreams_count > 0').order(dreams_count: :desc).each do |category| %>
    <%= link_to t(".#{category.name.downcase.gsub(' ', '_')}"), category_path(category), class: "btn btn-dark my-1" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= render 'group' %>

<%= render 'dreams/dreams', dreams: @category.dreams %>