config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  constraints ->(request) { request.env['warden'].user&.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  mount Sidekiq::Web => '/sidekiq'

  root 'dreams#index', defaults: { format: :html }

  resources :categories, only: %i[index show]

  resources :dreams do
    resources :comments
    post :search, on: :collection
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  resources :users, only: %i[show edit update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  skip_before_action :verify_authenticity_token
  before_action :moon_phase_data
  before_action :set_locale

  rescue_from CanCan::AccessDenied do |e|
    redirect_to request.referer || root_path, alert: e.message
  end

  private

  def moon_phase_data
    cookies[:moon_phase] ||= { value: MoonPhase.phase(request).to_json, expires: Time.zone.now + 1.hour }
    @moon_phase_data = JSON.parse(cookies[:moon_phase]).deep_symbolize_keys
  end

  def set_locale
    I18n.locale = params[:locale] || cookies[:locale] ||
                  http_accept_language.compatible_language_from(I18n.available_locales)
    cookies[:locale] = I18n.locale if params[:locale]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def moon_phase_image_tag(phase)
    image_tag("#{phase_name(phase)}.png")
  end

  def phase_name(phase)
    phase[:days].first[:moonphase_name].downcase.gsub(' ', '_')
  end
end

app/views/application/_header.html.erb
<div class="app-header">
  <nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <%= link_to 'Slumber', root_path, class: 'navbar-brand' %>
      <%= render 'search_form' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"><%= current_user&.name %></h5>
          <div class="avatar-wrapper">
            <%= image_tag current_user.avatar, class: "avatar-image" if user_signed_in? %>
          </div>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to t('.profile'), user_path(current_user), class: "nav-link" %>
                <%= link_to t('.log_out'), destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
                <%= link_to t('.new_dream'), new_dream_path, class: "nav-link active btn btn-secondary", "aria-current": "page" %>
              <% else %>
                <%= link_to t('.login'), new_user_session_path, class: "nav-link" %>
                <%= link_to t('.sign_up'), new_user_registration_path, class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <% if can? :manage, :all %>
                <a class="nav-link" href="/avo">Avo</a>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= t('.lang') %>
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <% if I18n.locale == :ru %>
                  <li><%= link_to "English", url_for(locale: :en), class: "dropdown-item" %></li>
                <% else %>
                  <li><%= link_to "Русский", url_for(locale: :ru), class: "dropdown-item" %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <svg width="80" height="80" viewBox="0 0 250 250" aria-hidden="true"></svg>
</div> 

app/views/application/_moon_phase.html.erb
<div class="col-md-2">
  <div class="card text-bg-dark p-3">
    <div class="card-header">
      <h5 class="card-title"><%= t(".#{phase_name(@moon_phase_data)}") %></h5>
    </div>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item text-bg-dark"> <%= t('.timezone') + @moon_phase_data[:timezone] %></li>
        <% @moon_phase_data[:days].first.except(:moonphase_name).each do |key, value| %>
          <li class="list-group-item text-bg-dark"><%= t(".#{key}") %>: <%= value %></li>
        <% end %>
        <%= moon_phase_image_tag(@moon_phase_data) %>
      </ul>
    </div>
  </div>
</div>

app/views/application/_search_form.html.erb
<%= simple_form_for :search, url: search_dreams_path,
                               wrapper: :inline_form, html: { class: "form-inline" },
                               data: { controller: 'search-form' } do |f| %>
  <div class="input-group">
    <%= f.input_field :search, class: "form-control", required: false, placeholder: t('.search_dreams'),
                                                      style: "width: 40%;", data: { search_form_target: "search" } %>
    <%= f.input_field :date, class: "form-control s_date", placeholder: t('.search_date'), data: { search_form_target: "date" } %>
    <span class="input-group-text btn btn-light" type='button' data-action="click->search-form#clear">
      <%= octicon "x", height: 20 %>
    </span>
    <%= f.submit t('.search_submit'), class: "input-group-append btn btn-info", data: { action: 'click->search-form#submit' } %>
  </div>
<% end %>

app/views/application/_toast.html.erb
<% flash.each do |type, msg| %>
  <div class="position-fixed bottom-0 end-0 p-3" data-controller="toast">
    <div class="toast bg-light text-dark" role="alert" aria-live="assertive" aria-atomic="true" data-toast-target='toast'>
      <div class="toast-header">
        <strong class="me-auto"> <%= type %> </strong>
        <small>just now</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= msg %>
      </div>
    </div>
  </div>
<% end %>